# Generated by Django 4.2.1 on 2023-05-10 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingTransaction",
            fields=[
                (
                    "transactionId",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("userId", models.IntegerField()),
                ("transactionAmount", models.FloatField()),
                ("transactionDueDate", models.DateTimeField()),
                ("transactionCurrencyId", models.IntegerField()),
                ("transactionFee", models.FloatField()),
                ("installmentNumber", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userId", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=180)),
                ("email", models.CharField(max_length=180)),
                ("password", models.CharField(max_length=180)),
                ("salt", models.CharField(max_length=8)),
                ("balance", models.FloatField()),
                ("accountCurrencyId", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transactionId",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("transactionDate", models.DateTimeField()),
                ("transactionAmount", models.FloatField()),
                ("transactionCurrencyId", models.IntegerField()),
                ("transactionFee", models.FloatField()),
                ("confirmed", models.BooleanField()),
                (
                    "recipientAccountId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactionRecipientAccountId",
                        to="debit_api.user",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactionUserId",
                        to="debit_api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=180)),
                ("lastName", models.CharField(max_length=180)),
                ("addressLine1", models.CharField(max_length=180)),
                ("addressLine2", models.CharField(max_length=180)),
                ("postCode", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("phoneNumber", models.CharField(max_length=20)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billingUserId",
                        to="debit_api.user",
                    ),
                ),
            ],
        ),
    ]
