# Generated by Django 4.2.1 on 2023-05-11 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("debit_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("cardId", models.IntegerField(primary_key=True, serialize=False)),
                ("cardNumber", models.CharField(max_length=16)),
                ("cardType", models.CharField(max_length=20)),
                ("cvv", models.CharField(max_length=3)),
                ("salt", models.CharField(max_length=30)),
                ("expiryDate", models.DateField()),
                ("name", models.CharField(max_length=180)),
                ("balance", models.FloatField()),
                ("accountCurrencyId", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="PendingTransaction",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="userId",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="recipientAccountId",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="userId",
        ),
        migrations.AlterField(
            model_name="billing",
            name="addressLine2",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name="billing",
            name="country",
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name="billing",
            name="postCode",
            field=models.CharField(max_length=8),
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="billing",
            name="cardId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billingCardId",
                to="debit_api.card",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="cardId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactionCardId",
                to="debit_api.card",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="recipientCardId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactionRecipientCardId",
                to="debit_api.card",
            ),
            preserve_default=False,
        ),
    ]
