# Generated by Django 4.2.1 on 2023-05-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "debit_api",
            "0002_card_delete_pendingtransaction_remove_billing_userid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="cardId",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="cardId",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="confirmed",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="recipientCardId",
        ),
        migrations.AddField(
            model_name="billing",
            name="card",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billingCard",
                to="debit_api.card",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="card",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactionCard",
                to="debit_api.card",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="recipient",
            field=models.CharField(default="test", max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="cardId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transactionId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
