# Generated by Django 4.2.1 on 2023-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debit_api", "0003_remove_billing_cardid_remove_transaction_cardid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="cardNumber",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="card",
            name="salt",
            field=models.CharField(max_length=60),
        ),
    ]
