# Generated by Django 4.2.1 on 2023-05-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("debit_api", "0005_currency_remove_card_accountcurrencyid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="email",
            field=models.CharField(default="test@email.com", max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="billing",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="billingCard",
                to="debit_api.card",
            ),
        ),
    ]
