# Generated by Django 4.2.1 on 2023-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debit_api", "0006_card_email_alter_billing_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transactionDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
